language: python
sudo: required
dist: trusty

python:
- 2.7

before_install:
- sudo apt-get install python-pip
- sudo pip install scapy

script:
- sudo python main.py

notifications:
  email:
    on_success: never
# More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications